KEEP ALL THE RESOURCES THAT YOUR GAME NEEDS IN THIS FOLDER. ALL
THE CONTENTS OF THIS FOLDER ARE ADDED TO THE BUILD, AND WILL BE
AVAILABLE WHEN YOU RUN YOUR GAME. THE FILES IN HERE ARE TREATED
AS THE RESOURCE FILES, NOT EXTERNAL FILES, AND THESE FILES WILL
BE PACKAGED INTO THE RUNNABLE JAR, AND THE WAR FILES IN THE GWT
AND DESKTOP BUILDS.

YOU CAN SAFELY DELETE THIS FILE NOW.